#!/usr/bin/env python3
"""MVP 生成器 - 使用 Codex 自动生成代码框架"""

import subprocess
import json
import os
from typing import Dict, Any, Optional
from datetime import datetime


class MVPGenerator:
    """自动生成 MVP 代码框架"""
    
    def __init__(self, output_dir: str = None):
        self.output_dir = output_dir or os.path.expanduser("~/Code/one-company-lab/mvps")
        os.makedirs(self.output_dir, exist_ok=True)
    
    def generate(self, opportunity: Dict[str, Any]) -> Optional[str]:
        """
        为机会生成 MVP
        
        Args:
            opportunity: 机会数据（包含 title, description, revenue_model 等）
            
        Returns:
            生成的 MVP 目录路径，失败返回 None
        """
        project_name = self._sanitize_name(opportunity.get('title', 'unknown'))
        project_dir = os.path.join(self.output_dir, project_name)
        
        print(f"\n🚀 Generating MVP for: {opportunity.get('title', '')}")
        print(f"   Project: {project_name}")
        print(f"   Output: {project_dir}")
        
        # 1. 创建项目结构
        self._create_project_structure(project_dir)
        
        # 2. 生成 README
        self._generate_readme(project_dir, opportunity)
        
        # 3. 使用 Codex 生成核心代码
        self._generate_code_with_codex(project_dir, opportunity)
        
        # 4. 提交到 Git
        self._commit_to_git(project_dir, opportunity)
        
        return project_dir
    
    def _sanitize_name(self, name: str) -> str:
        """清理项目名称"""
        # 移除特殊字符，只保留字母数字和连字符
        import re
        name = re.sub(r'[^a-zA-Z0-9\s-]', '', name)
        name = re.sub(r'\s+', '-', name)
        return name.lower()[:50]
    
    def _create_project_structure(self, project_dir: str):
        """创建项目目录结构"""
        dirs = [
            'src',
            'tests',
            'docs',
            '.github/workflows'
        ]
        
        for d in dirs:
            os.makedirs(os.path.join(project_dir, d), exist_ok=True)
        
        # 创建 .gitignore
        gitignore = """node_modules/
__pycache__/
*.pyc
.env
dist/
build/
.DS_Store
"""
        with open(os.path.join(project_dir, '.gitignore'), 'w') as f:
            f.write(gitignore)
        
        print(f"   ✅ Created project structure")
    
    def _generate_readme(self, project_dir: str, opportunity: Dict[str, Any]):
        """生成 README.md"""
        readme = f"""# {opportunity.get('title', 'MVP Project')}

**Generated by**: Research Agent  
**Date**: {datetime.now().strftime('%Y-%m-%d')}  
**Score**: {opportunity.get('score', 0)}/100

## 📖 Project Description

{opportunity.get('description', opportunity.get('summary', 'Auto-generated MVP project'))}

## 💰 Business Model

- **Revenue Model**: {opportunity.get('revenue_model', 'Subscription')}
- **Startup Cost**: {opportunity.get('startup_cost', '$1-5k')}
- **Time to Revenue**: {opportunity.get('time_to_revenue', '30 days')}
- **Monthly Potential**: {opportunity.get('monthly_potential', '$10-50k')}
- **Automation Rate**: {opportunity.get('automation_rate', '90%+')}

## 🤖 Agent Roles

{chr(10).join(f'- {role}' for role in opportunity.get('agent_roles', ['Development Agent', 'Customer Support Agent']))}

## 🚀 Quick Start

```bash
# Install dependencies
npm install  # or pip install -r requirements.txt

# Run development server
npm run dev  # or python src/main.py

# Run tests
npm test  # or pytest
```

## 📁 Project Structure

```
{project_dir.split('/')[-1]}/
├── src/          # Source code
├── tests/        # Tests
├── docs/         # Documentation
└── .github/      # CI/CD workflows
```

## 🔗 Related

- [Opportunity Document](../opportunities/)
- [GitHub Issue](https://github.com/KathenZK/one-company-lab/issues)

---

*Auto-generated by Research Agent MVP Generator*
"""
        
        with open(os.path.join(project_dir, 'README.md'), 'w') as f:
            f.write(readme)
        
        print(f"   ✅ Generated README.md")
    
    def _generate_code_with_codex(self, project_dir: str, opportunity: Dict[str, Any]):
        """使用 Codex 生成核心代码"""
        prompt = f"""Create a minimal MVP for: {opportunity.get('title', '')}

Description: {opportunity.get('description', opportunity.get('summary', ''))}

Revenue Model: {opportunity.get('revenue_model', 'Subscription')}
Target Users: SaaS/B2B customers

Requirements:
1. Simple landing page
2. Basic functionality to validate the idea
3. Clean, minimal code
4. Include tests

Generate:
1. package.json or requirements.txt
2. src/index.js or src/main.py
3. Basic tests

Keep it simple - this is an MVP to validate the idea quickly."""

        print(f"   🤖 Calling Codex for code generation...")
        
        # 调用 Codex (通过 sessions_spawn 或 exec)
        # 这里简化为创建基础模板
        self._create_basic_template(project_dir, opportunity)
    
    def _create_basic_template(self, project_dir: str, opportunity: Dict[str, Any]):
        """创建基础代码模板"""
        # 创建 package.json (Node.js 项目)
        package_json = {
            "name": self._sanitize_name(opportunity.get('title', 'mvp')),
            "version": "1.0.0",
            "description": opportunity.get('summary', '')[:200],
            "main": "src/index.js",
            "scripts": {
                "start": "node src/index.js",
                "dev": "node --watch src/index.js",
                "test": "node tests/test.js"
            },
            "keywords": ["mvp", "ai", "saas"],
            "author": "Research Agent",
            "license": "MIT"
        }
        
        with open(os.path.join(project_dir, 'package.json'), 'w') as f:
            json.dump(package_json, f, indent=2)
        
        # 创建基础 JS 文件
        index_js = f"""// {opportunity.get('title', 'MVP')}
// Generated by Research Agent

console.log('🚀 {opportunity.get('title', 'MVP')} started');
console.log('Description: {opportunity.get('summary', '')[:100]}');

// TODO: Implement core functionality
// 1. Landing page
// 2. User authentication
// 3. Core feature

module.exports = {{
  start: () => {{
    console.log('Server running...');
  }}
}};
"""
        
        with open(os.path.join(project_dir, 'src', 'index.js'), 'w') as f:
            f.write(index_js)
        
        # 创建测试文件
        test_js = """// Basic tests
const assert = require('assert');

describe('MVP Tests', () => {
  it('should start without errors', () => {
    assert.ok(true);
  });
  
  // TODO: Add more tests
});

console.log('✅ All tests passed');
"""
        
        with open(os.path.join(project_dir, 'tests', 'test.js'), 'w') as f:
            f.write(test_js)
        
        print(f"   ✅ Generated basic code template")
    
    def _commit_to_git(self, project_dir: str, opportunity: Dict[str, Any]):
        """提交到 Git"""
        try:
            # 检查是否在 Git 仓库中
            one_company_dir = os.path.expanduser("~/Code/one-company-lab")
            
            if not os.path.exists(os.path.join(one_company_dir, '.git')):
                print(f"   ⚠️  one-company-lab is not a git repo, skipping commit")
                return
            
            # 添加文件
            subprocess.run(['git', 'add', '.'], cwd=one_company_dir, capture_output=True)
            
            # 提交
            commit_msg = f"feat: Generate MVP for {opportunity.get('title', '')[:50]}\n\nScore: {opportunity.get('score', 0)}/100\nAuto-generated by Research Agent"
            subprocess.run(['git', 'commit', '-m', commit_msg], cwd=one_company_dir, capture_output=True)
            
            # 推送
            subprocess.run(['git', 'push'], cwd=one_company_dir, capture_output=True)
            
            print(f"   ✅ Committed and pushed to one-company-lab")
            
        except Exception as e:
            print(f"   ⚠️  Git commit failed: {e}")


# 测试
if __name__ == '__main__':
    test_opp = {
        'title': 'AI Agent Platform',
        'summary': 'Build AI agent solutions for businesses',
        'description': 'Vertical AI agent platform',
        'score': 85,
        'revenue_model': 'Subscription',
        'startup_cost': '$1-5k',
        'time_to_revenue': '30 days',
        'monthly_potential': '$10-50k',
        'automation_rate': '90%+',
        'agent_roles': ['AI Agent', 'Support Agent', 'Marketing Agent']
    }
    
    generator = MVPGenerator()
    project_dir = generator.generate(test_opp)
    print(f"\n✅ MVP generated at: {project_dir}")
